---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-systems
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: arc
  namespace: arc-systems
spec:
  interval: 10m0s
  type: oci
  url: oci://ghcr.io/actions/actions-runner-controller-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc
  namespace: arc-systems
spec:
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: arc
      version: latest
  interval: 10m0s
  install:
    createNamespace: true
