---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    providers:
      kubernetesGateway:
        enabled: true
    gateway:
      listeners:
        web:
          port: 8000
          protocol: HTTP
          namespacePolicy: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: api-gateway
  namespace: kube-system
spec:
  gatewayClassName: traefik
  listeners:
  - name: web
    port: 8000
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
# --- This gets created by ^^
# apiVersion: gateway.networking.k8s.io/v1
# kind: GatewayClass
# metadata:
#   name: traefik
# spec:
#   controllerName: traefik.io/gateway-controller
#
# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: Gateway
# metadata:
#   name: gateway
#   namespace: default
# spec:
#   gatewayClassName: traefik
#   listeners:
#   - name: http
#     protocol: HTTP
#     port: 8000
#     allowedRoutes:
#       namespaces:
#         from: All
