on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
jobs:
  build:
    runs-on: arc-runner-set
    steps:
    - uses: actions/checkout@v4
    - run: echo "Running on my own machine!"
